import type { Campaign, Supporter } from "./types"

export const campaigns: Campaign[] = [
  {
    id: "1",
    title: "Eco-Friendly Water Bottle with Built-in Purifier",
    description:
      "A reusable water bottle that purifies water on-the-go, reducing plastic waste and providing clean water anywhere.",
    image: "",
    goal: 10,
    raised: 8.5,
    daysLeft: 15,
    creator: "0x1a2b3c...",
    category: "technology",
    status: "active",
  },
  {
    id: "2",
    title: "Community Garden in Urban Neighborhood",
    description:
      "Creating a sustainable community garden to provide fresh produce and green space in an urban food desert.",
    image: "",
    goal: 5,
    raised: 3.2,
    daysLeft: 20,
    creator: "0x4d5e6f...",
    category: "community",
    status: "active",
  },
  {
    id: "3",
    title: "Virtual Reality Educational Platform",
    description:
      "An immersive VR platform that makes learning accessible and engaging for students of all ages and backgrounds.",
    image: "",
    goal: 15,
    raised: 15,
    daysLeft: 0,
    creator: "0x7g8h9i...",
    category: "education",
    status: "completed",
  },
  {
    id: "4",
    title: "Sustainable Fashion Collection",
    description:
      "A clothing line made from recycled materials and sustainable fabrics, promoting ethical fashion practices.",
    image: "",
    goal: 8,
    raised: 2.1,
    daysLeft: 0,
    creator: "0xjk1l2m...",
    category: "art",
    status: "expired",
  },
  {
    id: "5",
    title: "Solar-Powered Smartphone Charger",
    description: "A compact, efficient solar charger that can power your devices anywhere with just sunlight.",
    image: "",
    goal: 7,
    raised: 4.3,
    daysLeft: 12,
    creator: "0xn3o4p5...",
    category: "technology",
    status: "active",
  },
  {
    id: "6",
    title: "Documentary on Ocean Conservation",
    description:
      "A powerful documentary highlighting the challenges facing our oceans and the people working to protect them.",
    image: "",
    goal: 12,
    raised: 6.8,
    daysLeft: 25,
    creator: "0xq7r8s9...",
    category: "environment",
    status: "active",
  },
  {
    id: "7",
    title: "Accessible Playground for All Children",
    description: "Building an inclusive playground designed for children of all abilities to play together.",
    image: "",
    goal: 20,
    raised: 15.7,
    daysLeft: 18,
    creator: "0xt2u3v4...",
    category: "community",
    status: "active",
  },
  {
    id: "8",
    title: "AI-Powered Language Learning App",
    description:
      "An innovative app that uses artificial intelligence to personalize language learning for faster fluency.",
    image: "",
    goal: 9,
    raised: 7.2,
    daysLeft: 8,
    creator: "0xw5x6y7...",
    category: "education",
    status: "active",
  },
  {
    id: "9",
    title: "Biodegradable Packaging Solution",
    description: "Developing eco-friendly packaging that breaks down naturally, reducing environmental impact.",
    image: "",
    goal: 11,
    raised: 9.9,
    daysLeft: 5,
    creator: "0xz1a2b3...",
    category: "environment",
    status: "active",
  },
]

export const supporters: Supporter[] = [
  {
    id: "1",
    walletAddress: "0x71C7656EC7ab88b098defB751B7401B5f6d8976F",
    amount: 2.5,
    date: "2 days ago",
    campaignId: "1",
    campaignTitle: "Eco-Friendly Water Bottle with Built-in Purifier",
  },
  {
    id: "2",
    walletAddress: "0x2546BcD3c84621e976D8185a91A922aE77ECEc30",
    amount: 1.0,
    date: "3 days ago",
    campaignId: "2",
    campaignTitle: "Community Garden in Urban Neighborhood",
  },
  {
    id: "3",
    walletAddress: "0xbDA5747bFD65F08deb54cb465eB87D40e51B197E",
    amount: 3.2,
    date: "5 days ago",
    campaignId: "1",
    campaignTitle: "Eco-Friendly Water Bottle with Built-in Purifier",
  },
  {
    id: "4",
    walletAddress: "0xdD870fA1b7C4700F2BD7f44238821C26f7392148",
    amount: 0.5,
    date: "1 week ago",
    campaignId: "3",
    campaignTitle: "Virtual Reality Educational Platform",
  },
  {
    id: "5",
    walletAddress: "0x8fD00f170FDf3772C5ebdCD90bF257316c69BA45",
    amount: 1.8,
    date: "1 week ago",
    campaignId: "2",
    campaignTitle: "Community Garden in Urban Neighborhood",
  },
  {
    id: "6",
    walletAddress: "0x1aE0EA34a72D944a8C7603FfB3eC30a6669E454C",
    amount: 4.0,
    date: "2 weeks ago",
    campaignId: "5",
    campaignTitle: "Solar-Powered Smartphone Charger",
  },
  {
    id: "7",
    walletAddress: "0x0A098Eda01Ce92ff4A4CCb7A4fFFb5A43EBC70DC",
    amount: 2.2,
    date: "2 weeks ago",
    campaignId: "6",
    campaignTitle: "Documentary on Ocean Conservation",
  },
  {
    id: "8",
    walletAddress: "0xCA35b7d915458EF540aDe6068dFe2F44E8fa733c",
    amount: 1.5,
    date: "3 weeks ago",
    campaignId: "1",
    campaignTitle: "Eco-Friendly Water Bottle with Built-in Purifier",
  },
  {
    id: "9",
    walletAddress: "0x14723A09ACff6D2A60DcdF7aA4AFf308FDDC160C",
    amount: 0.8,
    date: "3 weeks ago",
    campaignId: "4",
    campaignTitle: "Sustainable Fashion Collection",
  },
  {
    id: "10",
    walletAddress: "0x4B0897b0513fdC7C541B6d9D7E929C4e5364D2dB",
    amount: 3.5,
    date: "1 month ago",
    campaignId: "3",
    campaignTitle: "Virtual Reality Educational Platform",
  },
]
